import 'package:migozz_app/features/auth/presentation/register/user_details/components/interest_section_model.dart';

final List<InterestSectionModel> sections = [
  InterestSectionModel(
    title: "Going Out",
    options: [
      "Concerts",
      "Museums & Galleries",
      "Yoga",
      "Comedy",
      "Theater",
      "Clubs",
      "Bars",
      "Karaoke",
      "Film Festivals",
      "Lounging",
    ],
  ),
  InterestSectionModel(
    title: "Sports",
    options: [
      "Football",
      "Soccer",
      "Hockey",
      "Sports News",
      "Fishing",
      "Basketball",
      "Cricket",
      "Pickleball",
      "Gymnastics",
      "Horse Riding",
      "MMA",
      "Tennis",
      "Swimming",
      "Snowboarding",
      "Gym",
      "Surfing",
      "Skiing",
      "Baseball",
      "Golf",
      "Boxing",
    ],
  ),
  InterestSectionModel(
    title: "Film & TV",
    options: [
      "Drama",
      "Thriller",
      "Crime",
      "Fantasy",
      "Anime",
      "Sci-fi",
      "Mystery",
      "Comedy",
      "Romance",
      "Action",
      "Horror",
    ],
  ),
  InterestSectionModel(
    title: "Values & Traits",
    options: [
      "Intelligence",
      "Positivity",
      "Confidence",
      "Family Oriented",
      "Ambition",
      "Creativity",
      "Empathy",
    ],
  ),
  InterestSectionModel(
    title: "Traveling",
    options: [
      "Beaches",
      "Spa Weekends",
      "Staycations",
      "Backpacking",
      "Winter Sports",
      "Hiking Trips",
      "Road Trips",
      "Exploring New Cities",
      "Fishing Trips",
      "Camping",
    ],
  ),
  InterestSectionModel(
    title: "Business",
    options: [
      "Entrepreneurship",
      "Sales",
      "Real Estate",
      "Crypto",
      "Marketing",
      "Stocks",
    ],
  ),
  InterestSectionModel(
    title: "Creativity",
    options: [
      "Writing",
      "Photography",
      "Dancing",
      "Singing",
      "Design",
      "Content Creation",
      "Art",
      "Make-up",
    ],
  ),
  InterestSectionModel(
    title: "Staying In",
    options: [
      "Reading",
      "Baking",
      "Take Out",
      "Cooking",
      "Board Games",
      "Gardening",
      "Video Games",
    ],
  ),
  InterestSectionModel(
    title: "Pets",
    options: [
      "Snakes",
      "Birds",
      "Fish",
      "Turtles",
      "Hamsters",
      "Cats",
      "Dogs",
      "Lizards",
      "Rabbits",
    ],
  ),
];
