name: migozz_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  qr_flutter: ^4.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_dotenv: ^6.0.0

  permission_handler: ^12.0.1 # permisos
  record: ^6.1.1 # grabar audio
  just_audio: ^0.10.5 # reproducir audio
  audio_waveforms: ^1.3.0 # mostrar ola de audio
  path_provider: ^2.1.5 # necesaria para guardar el audio
  intl_phone_field: ^3.2.0

  image_picker: ^1.2.0 # imagenes

  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  http: ^1.5.0 # validar email con OTP
  flutter_svg: ^2.0.9
  go_router: ^16.2.2 # refactor de la naveegacion
  google_generative_ai: ^0.4.6
  url_launcher: ^6.3.0
  location: ^8.0.1

  firebase_core: ^3.4.0 # necesaria para firebase
  cloud_firestore: ^5.6.0 # necesaria para firestore
  google_sign_in: ^6.2.1 # necesario para el inicio con google
  firebase_auth: ^5.1.4 # para auth

  cloud_functions: ^5.6.2
  firebase_dynamic_links: ^6.1.10
  flutter_appauth: ^10.0.0
  firebase_storage: ^12.4.10
  share_plus: ^7.2.1
  cached_network_image: ^3.4.1

dev_dependencies:
  tutorial_coach_mark: ^1.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/Migozz_SinFONDO.svg"
  adaptive_icon_background: "#D43AB6"
  adaptive_icon_foreground: "assets/icon/Migozz.svg"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/icons/social_networks/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
