// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQdfYVFIgQydVvo2gwmYfD2FGOUpELX4o',
    appId: '1:895592952324:web:9b8c3609b0109c70727b51',
    messagingSenderId: '895592952324',
    projectId: 'migozz-e2a21',
    authDomain: 'migozz.com',
    databaseURL: 'https://migozz-e2a21-default-rtdb.firebaseio.com',
    storageBucket: 'migozz-e2a21.appspot.com', // ✅ corregido
    measurementId: 'G-BFN3GXRHXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2ySPBZ6BiF-LvRE2_W1AgxYVpAmGgWQ',
    appId: '1:895592952324:android:5da231d882586ecd727b51',
    messagingSenderId: '895592952324',
    projectId: 'migozz-e2a21',
    databaseURL: 'https://migozz-e2a21-default-rtdb.firebaseio.com',
    storageBucket: 'migozz-e2a21.appspot.com', // ✅ corregido
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPtroR20XQb1ukJDwN_8wX5ek4H99rPsE',
    appId: '1:895592952324:ios:c255099133ae2ef5727b51',
    messagingSenderId: '895592952324',
    projectId: 'migozz-e2a21',
    databaseURL: 'https://migozz-e2a21-default-rtdb.firebaseio.com',
    storageBucket: 'migozz-e2a21.appspot.com', // ✅ corregido
    androidClientId:
        '895592952324-acochpgr4ch4o97669jjpafeosgv7khg.apps.googleusercontent.com',
    iosClientId:
        '895592952324-as49khg1fbfm3jllms7nskqd06ht7jto.apps.googleusercontent.com',
    iosBundleId: 'com.migozz.migozzApp',
  );
}
